<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net461</TargetFramework>
    <PlatformTarget>x86</PlatformTarget>
    <LangVersion>7.3</LangVersion>
    <AssemblyName>DJMaxEditor.Core.Tests</AssemblyName>
    <RootNamespace>DJMaxEditor.Core.Tests</RootNamespace>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DJMaxEditor.Core\DJMaxEditor.Core.csproj" />
  </ItemGroup>
</Project>
